app/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('health/', views.health, name='health'),
#    path('en/', views.index, name='index'),
    path('lang/<str:lang>/', views.set_language, name='set_language'),
    path('checks/new/', views.checks_new, name='checks_new'),
    path('checks/create/', views.checks_create, name='checks_create'),
    path('checks/finalize/<int:pk>/', views.checks_finalize, name='checks_finalize'),
    path('checks/show/<int:pk>/', views.checks_show, name='checks_show'),
    path('checks/index/', views.checks_index, name='checks_index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('services/index/', views.services_index, name='services_index'),
    path('favicon\.ico',RedirectView.as_view(url='/static/images/favicon.ico')),
    path('', views.index, name='index'),
]

armatus/urls.py
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext_lazy as _
from django.urls import include, path

urlpatterns = [
    path('generador/', include('app.urls')),
    path('generador/admin/', admin.site.urls),
]

# urlpatterns += i18n_patterns(
#     path('generador/', include('app.urls')),
# )

app/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _
from datetime import datetime


class Check(models.Model):
    id = models.AutoField(
        primary_key=True,
        null=False)
    user = models.ForeignKey(
        User,
        null=False,
        default=None,
        verbose_name=_('user'),
        on_delete = models.CASCADE)
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('created_at'))
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('updated_at'))
    start_time = models.TimeField(
        null=False,
        verbose_name=_('start_time'))
    end_time = models.TimeField(
        null=True,
        blank=True,
        verbose_name=_('end_time'))
    operating_hours = models.DurationField(
        null=False,
        verbose_name=_('operating_hours'))
    starts = models.IntegerField(
        null=False,
        verbose_name=_('starts'))
    voltage_1 = models.IntegerField(
        null=False,
        verbose_name=_('voltage_1'))
    voltage_2 = models.IntegerField(
        null=False,
        verbose_name=_('voltage_2'))
    voltage_3 = models.IntegerField(
        null=False,
        verbose_name=_('voltage_3'))
    tank = models.DecimalField(
        max_digits=38,
        decimal_places=3,
        null=False,
        verbose_name=_('tank'))
    observations = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('observations'))

    class Meta:
        db_table = 'checks'
        verbose_name = _('Check')
        verbose_name_plural = _('Checks')

    def __unicode__(self):
        return str(format(self.created_at, "%d-%m-%Y, %H:%S"))

    def __str__(self):
        return format(self.created_at, "%d-%m-%Y, %H:%S")

    def operation_hours(self):
        ts = self.operating_hours.total_seconds()
        h = ts//3600
        m = (ts%3600)//60
        s = (ts%3600)%60
        return "{}:{}".format(int(h),int(m))


class Service(models.Model):
    id = models.AutoField(
        primary_key=True,
        null=False)
    user = models.ForeignKey(
        User,
        null=False,
        default=None,
        verbose_name=_('user'),
        on_delete = models.CASCADE)
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name=_('created_at'))
    updated_at = models.DateTimeField(
        auto_now=True,
        verbose_name=_('updated_at'))
    hours = models.IntegerField(
        null=False,
        verbose_name=_('hours'))
    oil_type = models.CharField(
        max_length=254,
        null=True,
        blank=True,
        verbose_name=_('oil_type'))
    oil = models.BooleanField(
        default=False,
        verbose_name=_('oil'))
    oil_filter = models.BooleanField(
        default=False,
        verbose_name=_('oil_filter'))
    fuel = models.BooleanField(
        default=False,
        verbose_name=_('fuel'))
    fuel_filter = models.BooleanField(
        default=False,
        verbose_name=_('fuel_filter'))
    air_filter = models.BooleanField(
        default=False,
        verbose_name=_('air_filter'))
    refrigerant = models.BooleanField(
        default=False,
        verbose_name=_('refrigerant'))
    battery = models.BooleanField(
        default=False,
        verbose_name=_('battery'))
    next_service_date = models.DateField(
        null=True,
        verbose_name=_('next_service_date'))
    next_service_hours = models.IntegerField(
        null=True,
        verbose_name=_('next_service_hours'))
    observations = models.TextField(
        null=True,
        blank=True,
        verbose_name=_('observations'))

    class Meta:
        db_table = 'services'
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __unicode__(self):
        return str(format(self.created_at, "%d-%m-%Y, %H:%S"))

    def __str__(self):
        return format(self.created_at, "%d-%m-%Y, %H:%S")
    

app/forms.py
# -*- coding: utf-8 -*-
from django import forms
import logging
from .models import Check
from datetimewidget.widgets import DateTimeWidget
from django.utils.translation import ugettext as _
from django.conf import settings
from datetime import datetime
from django.contrib.auth.models import User
from durationfield.forms import DurationField as FDurationField
from django.conf import settings


class CheckForm(forms.ModelForm):
    start_time = forms.TimeField(
        required=False,
        label=_('start_time'))
    end_time = forms.TimeField(
        required=False,
        label=_('end_time'))
    operating_hours = FDurationField(
        required=True,
        label=_('operating_hours'))
    starts = forms.IntegerField(
        required=True,
        label=_('starts'))
    voltage_1 = forms.IntegerField(
        required=True,
        label=_('voltage_1'))
    voltage_2 = forms.IntegerField(
        required=True,
        label=_('voltage_2'))
    voltage_3 = forms.IntegerField(
        required=True,
        label=_('voltage_3'))
    tank = forms.DecimalField(
        required=True,
        max_value=1,
        min_value=0,
        max_digits=3,
        decimal_places=3,
        label=_('tank'))
    user = forms.ModelChoiceField(
        queryset=User.objects.all(),
        to_field_name = "id",
        required = True,
        label=_('user'))
    observations = forms.CharField(
        required=False,
        widget=forms.Textarea,
        label=_('observations'))

    def clean(self):
        cleaned_data = super(CheckForm, self).clean()

    class Meta:
        model = Check
        fields = ('start_time', 'end_time', 'operating_hours','starts','tank',
                  'voltage_1','voltage_2','voltage_3','user','observations')

templates/checks/index.html
{% extends "base.html" %}
{% load i18n %}
{% load staticfiles %}

{% block content %}
 
<div class="panel panel-default">
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr class="active">
          <th>{{ _('Created_at') }}</th>
          <th>{{ _('Start_time') }}</th>
          <th>{{ _('End_time') }}</th>
          <th>{{ _('Starts') }}</th>
          <th>{{ _('Operating_hours') }}</th>
          <th>{{ _('Voltage_1') }}</th>
          <th>{{ _('Voltage_2') }}</th>
          <th>{{ _('Voltage_3') }}</th>
          <th>{{ _('Tank') }}</th>
        </tr>
      </thead>
      <tbody>
        {% if checks %} {% for check in checks %}
        <tr>
          <td title="{{ check.observation|default:'' }}">
            <a href="{% url 'checks_show' check.pk %}" >{{ check.created_at|default:'' }}<a/>
          </td>
          <td>{{ check.start_time|date:'H:i'|default:'' }} </td>
          <td>
            {% if check.end_time %} 
              {{ check.end_time|date:'H:i'|default:'' }}
            {% else %}
            <a href="{% url 'checks_finalize' check.pk %}" title="{{ _('Finalize') }}">
              <i class="glyphicon glyphicon-dashboard"></i>
            </a>
            {% endif %} 
          </td>
          <td>{{ check.starts|default:'' }} </td>
          <td>{{ check.operating_hours|default:'' }} </td>
          <td>
            {{ check.voltage_1|default:'' }}
          </td>
          <td>
            {{ check.voltage_2|default:'' }}
          </td>
          <td>
            {{ check.voltage_3|default:'' }}
          </td>
          <td>
            {% widthratio check.tank 1 100 %}%
          </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
          <td colspan='6'>{{ _('withouth_results') }}</td>
        </tr>
        {% endif %}
      </tbody>
    </table>
    <table class="table table-bordered table-hover">
      <tr>
        <td style="width:5%;text-align:center" title="{{ _('New_check') }}">
          <a href="{% url 'checks_new' %}" id="add_row" >
            <i class=" glyphicon glyphicon-plus-sign"></i>
          </a>
        </td>
        <td></td>
      </tr>
    </table>

  </div>
</div>

{% endblock %}

templates/checks/new.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

<div class="well bs-component">
  <form class="form-horizontal" action="{% url 'checks_create' %}" method="post">
    {% csrf_token %}
    <fieldset>
      <legend>{{ _('Checks_request') }}</legend>
      <div class="form-group" title="{{ _('Start_title') }}">
        <label class="col-sm-2 control-label" for="id_starts">{{ _('Starts') }}</label>
        <div class="col-sm-2">

          <div class="input-group">
            <div class="input-group-btn">
              <button type="button" id="sp0down" class="btn btn-primary" aria-label="Bold">
                <span class="glyphicon glyphicon-minus"></span>
              </button>
            </div>
            <input class="form-control text-center" type="text" name="starts" id="id_starts"
                   value="{{ form.starts.value|default:'' }}"/>
            <div class="input-group-btn">
              <button type="button" id="sp0up" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
              </button>
            </div>
           
          </div>
        </div>
      </div>
      <script>
        $( "#sp0down" ).on( "click", function() {
          $( "#id_starts" ).val( parseInt($( "#id_starts" ).val())-1);
        });
        $( "#sp0up" ).on( "click", function() {
          $( "#id_starts" ).val( parseInt($( "#id_starts" ).val())+1);
        });
      </script>
  
      
      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_operating_hours">{{ _('Operating_hours') }}</label>
        <div class="col-sm-2">
          <div class="input-group" >
            <span class="input-group-addon" id="basic-addon1" >
              <span class="glyphicon glyphicon-time" id="id_operating_hours_icon" aria-hidden="true"></span>
            </span>
            <input class="form-control" type="text" name="operating_hours" id="id_operating_hours"
                   value="{{ form.operating_hours.value|default:'' }}"/>
          </div>
        </div>
      </div>
      
     
      <script type="text/javascript">
        $("#id_operating_hours").timepicker({
                minuteStep: 1,
                template: dropdown,
                maxHours:1000,
                appendWidgetTo: 'body',
                showSeconds: false,
                showMeridian: false,
                showInputs: false,
                explicitMode: true,
                defaultTime: '{{ form.operating_hours.value|default:'' }}'
            });
      </script>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_date_from">{{ _('Voltages') }}</label>
        <div class="col-sm-2">
          <div class="input-group number-spinner">
            <div class="input-group-btn">
              <button type="button" id="sp1up" class="btn btn-primary" aria-label="Bold">
                <span class="glyphicon glyphicon-minus"></span>
              </button>
            </div>
            <input class="form-control text-center" type="text" name="voltage_1" id="id_voltage_1"
                   value="{{ form.voltage_1.value|default:'' }}"/>
            <div class="input-group-btn">
              <button type="button" id="sp1down" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
              </button>
            </div>
          </div>
        </div>
        <label class="control-label"></label>
        <div class="col-sm-2">
          <div class="input-group number-spinner">
            <div class="input-group-btn">
              <button type="button" id="sp2up" class="btn btn-primary" aria-label="Bold">
                <span class="glyphicon glyphicon-minus"></span>
              </button>
            </div>
            <input class="form-control text-center" type="text" name="voltage_2" id="id_voltage_2"
                   value="{{ form.voltage_2.value|default:'' }}"/>
            <div class="input-group-btn">
              <button type="button" id="sp2down" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
              </button>
            </div>
          </div>
        </div>
        <label class="control-label"></label>
        <div class="col-sm-2">
          <div class="input-group number-spinner">
            <div class="input-group-btn">
              <button type="button" id="sp3up" class="btn btn-primary" aria-label="Bold">
                <span class="glyphicon glyphicon-minus"></span>
              </button>
            </div>
            <input class="form-control text-center" type="text" name="voltage_3" id="id_voltage_3"
                   value="{{ form.voltage_3.value|default:'' }}"/>
            <div class="input-group-btn">
              <button type="button" id="sp3down" class="btn btn-primary">
                <span class="glyphicon glyphicon-plus"></span>
              </button>
            </div>
          </div>
        </div>
      </div>
      <script>
        $( "#sp1up" ).on( "click", function() {
          $( "#id_voltage_1" ).val( parseInt($( "#id_voltage_1" ).val())-1);
        });
        $( "#sp1down" ).on( "click", function() {
          $( "#id_voltage_1" ).val( parseInt($( "#id_voltage_1" ).val())+1);
        });
        $( "#sp2up" ).on( "click", function() {
          $( "#id_voltage_2" ).val( parseInt($( "#id_voltage_2" ).val())-1);
        });
        $( "#sp2down" ).on( "click", function() {
          $( "#id_voltage_2" ).val( parseInt($( "#id_voltage_2" ).val())+1);
        });
        $( "#sp3up" ).on( "click", function() {
          $( "#id_voltage_3" ).val( parseInt($( "#id_voltage_3" ).val())-1);
        });
        $( "#sp3down" ).on( "click", function() {
          $( "#id_voltage_3" ).val( parseInt($( "#id_voltage_3" ).val())+1);
        });
      </script>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_tank">
          <span style="margin-right:5px;">{{ _('Tank') }}</span>
          <span id="rangue_value" style="width:30px;float: right;"></span>
        </label>
        
        <div class="col-sm-4">
          <div id="slider" class="slider">
            <ul class="colors">
              <li class="green first-child">0</li>
              <li class="yellow">1/4</li>
              <li class="red">3/4</li>
              <li class="white">1</li>
              <li class="orange">1/2</li>
            </ul>
            <input class="slider-input"
                   type="range"
                   name="tank" 
                   min="0"
                   max="1"
                   id="slider"
                   step="0.05"
                   value="{{ form.tank.value }}"
                   data-orientation="horizontal">

          </div>
        </div>
      </div>
      <br>
      <br>
      
      <script>
        $( document ).ready(function() {

        $('input[type="range"]').rangeslider({
          polyfill: false,
          onSlide: function(position, value) {
            $( "#rangue_value" ).text( parseInt(value*100)+'%');
          },
          onInit: function() {
            $( "#rangue_value" ).text('{% widthratio form.tank.value 1 100 %}' + '%');
          },
          onSlideEnd: function(position, value) {
            $( "#rangue_value" ).text(parseInt(value*100)+ '%');
        }
        });
        
        });
      </script>
      
      <div class="form-group" title="{{ _('Observations') }}">
        <label class="col-sm-2 control-label" for="id_objectives">{{ _('Observations') }}</label>
        <div class="col-sm-6">
          <textarea class="form-control " name="observations" id="id_observations"
                    rows="3">{{ check.observations|default:'' }}</textarea>
        </div>
      </div>
      <br>
      <div class="form-group pull-right">
        <div class="col-xs-12">
          <button type="submit" class="btn btn-primary">{{ _('Send_application') }}</button>
        </div>
      </div>
    </fieldset>
  </form>
</div>
{% endblock %}

templates/checks/show.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}

    
<div class="well bs-component">
  <form class="form-horizontal" action="{% url 'index' %}" method="get">
    <fieldset>
      <legend>{{ _('Checks_show') }}</legend>
            
      <div class="form-group" title="{{ _('Start_title') }}">
        <label class="col-sm-2 control-label" for="id_starts">{{ _('Starts') }}</label>
        <div class="col-sm-2">
          <input class="form-control" type="text" name="starts" id="id_starts"
                 value="{{ form.starts.value|default:'' }}" readonly="" />
        </div>
      </div>

      
      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_operating_hours">{{ _('Operating_hours') }}</label>
        <div class="col-sm-2">
          <div class="input-group" >
            <span class="input-group-addon" id="basic-addon1" >
              <span class="glyphicon glyphicon-time" id="id_operating_hours_icon" aria-hidden="true"></span>
            </span>
            <input class="form-control" type="text" name="operating_hours" id="id_operating_hours"
                   value="{{ form.operating_hours.value|default:'' }}" readonly="" />
          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_date_from">{{ _('Date') }}</label>
        <div class="col-sm-2">
          <div class="input-group" >
            <input class="form-control" type="text" name="voltage_1" id="id_voltage_1"
                   value="{{ check.created_at|default:'' }}"  readonly=""/>
          </div>
        </div>
      </div>

      <div class="form-group">      
        <label class="control-label col-sm-2">{{ _('Start_time') }}</label>
        <div class="col-sm-2">
          <div class="input-group">
            <input class="form-control" type="text" name="voltage_2" id="id_voltage_2"
                   value="{{ check.start_time|default:'' }}"  readonly=""/>
          </div>
        </div>
        <label class="control-label col-sm-2">{{ _('End') }}</label>
        <div class="col-sm-2">
          <div class="input-group">
            <input class="form-control" type="text" name="voltage_3" id="id_voltage_3"
                   value="{{ check.end_time|default:'' }}"  readonly=""/>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_date_from">{{ _('Voltages') }}</label>
        <div class="col-sm-2">
          <div class="input-group" >
            <input class="form-control" type="text" name="voltage_1" id="id_voltage_1"
                   value="{{ form.voltage_1.value|default:'' }}"  readonly=""/>
          </div>
        </div>
        <label class="control-label"></label>
        <div class="col-sm-2">
          <div class="input-group">
            <input class="form-control" type="text" name="voltage_2" id="id_voltage_2"
                   value="{{ form.voltage_2.value|default:'' }}"  readonly=""/>
          </div>
        </div>
        <label class="control-label"></label>
        <div class="col-sm-2">
          <div class="input-group">
            <input class="form-control" type="text" name="voltage_3" id="id_voltage_3"
                   value="{{ form.voltage_3.value|default:'' }}"  readonly=""/>
          </div>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 control-label" for="id_tank">{{ _('Tank') }}</label>
        <div class="col-sm-2">
          <input class="form-control" type="text" name="voltage_3" id="id_voltage_3"
                 value="{% widthratio check.tank 1 100 %}%"  readonly=""/>
          <small id="id_complete_resource" class="form-text text-muted">&nbsp;</small>
        </div>
      </div>

      <div class="form-group" title="{{ _('Observations') }}">
        <label class="col-sm-2 control-label" for="id_objectives">{{ _('Observations') }}</label>
        <div class="col-sm-6">
          <textarea class="form-control " name="observations" id="id_observations"
                    rows="3" readonly="">{{ check.observations|default:'' }}</textarea>
        </div>
      </div>

      <br>
      <div class="form-group pull-right">
        <div class="col-xs-12">
          <a class="btn btn-primary" href="{% url 'index' %}" role="button">{{ _('Back') }}</a>
        </div>
      </div>

    </fieldset>
  </form>
</div>

{% endblock %}